<?php
    function simple_registration_form_alter(&$form, &$form_state, $form_id) {
      if($form_id == 'registration_form') {
        $form['state']['#access'] = 0;
        $form['who_message']['#access'] = 0;
      }

      if($form_id == 'item__node_form') {
        global $user;
        $form['field_request_item']['#access'] = 0;
        $form['field_owner']['und'][0]['target_id']['#default_value'] = $user->name;
      }
    }
